import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/util/StoreProvider";
import LoginModal from "@/components/Modals/LoginModal";
import SignupModal from "@/components/Modals/SignupModal";
import ForgotPasswordModal from "@/components/Modals/ForgotPasswordModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-full overflow-x-hidden`}
        >
          {children}
        </body>
        <SignupModal />
        <LoginModal />
        <ForgotPasswordModal />
      </StoreProvider>
    </html>
  );
}
